apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  JAVA_OPTS: "-Xmx256m"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http"
  SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED: "true"
  SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_LOWER_CASE_SERVICE_ID: "true"