
apiVersion: v1
kind: ConfigMap
metadata:
  name: connect-config
data:
  CONNECT_BOOTSTRAP_SERVERS: "kafka"
  CONNECT_REST_ADVERTISED_HOST_NAME: "connect"
  CONNECT_GROUP_ID: "compose-connect-group"
  CONNECT_CONFIG_STORAGE_TOPIC: "docker-connect-configs"
  CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
  CONNECT_OFFSET_STORAGE_TOPIC: "docker-connect-offsets"
  CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
  CONNECT_STATUS_STORAGE_TOPIC: "docker-connect-status"
  CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
  CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
  CONNECT_VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
  CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http"
  CONNECT_PLUGIN_PATH: ""/usr/share/java,/usr/share/confluent-hub-components""
  test: "[ "CMD", "curl", "-f", "http"
  interval: "10s"
  timeout: "5s"
  retries: "5"
  start_period: "30s"