apiVersion: v1
kind: ConfigMap
metadata:
  name: connection-service-config
data:
  JAVA_OPTS: "-Xmx256m"
  EUREKA_SERVER_ADDRESS: "http"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka"
  SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL: "http"
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
  EUREKA_INSTANCE_NON_SECURE_PORT: "8001"
  SERVER_PORT: "8001"