apiVersion: v1
kind: ConfigMap
metadata:
  name: control-center-config
data:
  CONTROL_CENTER_BOOTSTRAP_SERVERS: "kafka"
  CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http"
  CONTROL_CENTER_CONNECT_CONNECT-DEFAULT_CLUSTER: "connect"
  CONTROL_CENTER_REPLICATION_FACTOR: "1"
  CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: "1"
  CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: "1"
  CONFLUENT_METRICS_TOPIC_REPLICATION: "1"
  CONTROL_CENTER_KAFKA_CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"