apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  KAFKA_NODE_ID: "1"
  KAFKA_PROCESS_ROLES: "broker,controller"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER"
  KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka"
  KAFKA_LISTENERS: "PLAINTEXT"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT"
  KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
  CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
  KAFKA_JMX_PORT: "9101"
  KAFKA_JMX_HOSTNAME: "localhost"
  KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
  test: "[ "CMD", "kafka-cluster", "cluster-id", "--bootstrap-server", "localhost"
  interval: "10s"
  timeout: "10s"
  retries: "10"
  start_period: "30s"