
apiVersion: v1
kind: ConfigMap
metadata:
  name: posts-service-config
data:
  KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL: "http"
  JAVA_OPTS: "-Xmx256m"
  EUREKA_SERVER_ADDRESS: "http"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka"
  SPRING_DATASOURCE_URL: "jdbc"
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
  EUREKA_INSTANCE_NON_SECURE_PORT: "8002"
  SERVER_PORT: "8002"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "create-drop"
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"