apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL: "http"
  JAVA_OPTS: "-Xmx256m"
  SPRING_DATASOURCE_URL: "jdbc"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "Manish@2009"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka"
  SERVER_PORT: "8003"
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
  EUREKA_INSTANCE_NON_SECURE_PORT: "8003"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "create-drop"
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"