spring:
  main:
    banner-mode: off
  application:
    name: posts-service

  datasource:
    url: jdbc:postgresql://${DB_SERVICE:posts_db}:5432/${DB_NAME:Posts_Service}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:Manish@2009}

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      acks: all
      retries: 5
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://schema-registry:8081

  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
          producer-properties:
            schema.registry.url: http://schema-registry:8081

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://discovery-service:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

server:
  port: 8001
  servlet:
    context-path: /posts