apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: posts-db
spec:
  selector:
    matchLabels:
      app: posts-db
  serviceName: posts-db
  replicas: 1
  template:
    metadata:
      labels:
        app: posts-db
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        resources:
          limits:
            memory: "200Mi"
            cpu: "200m"
          requests:
            memory: "100Mi"
            cpu: "100m"
        env:
          - name: POSTGRES_DB
            value: Posts_Service
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: Manish@2009
          - name: PGDATA
            value: /var/lib/postgres/data/pgdata
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgres/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
      storageClassName: "ebs-sc" # Standard EBS storage class for EKS us-east-1

---

apiVersion: v1
kind: Service
metadata:
  name: posts-db
spec:
  clusterIP: None
  selector:
    app: posts-db
  ports:
  - port: 5432
    targetPort: 5432