
apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-center
  labels:
    app: control-center
spec:
  replicas: 1
  selector:
    matchLabels:
      app: control-center
  template:
    metadata:
      labels:
        app: control-center
    spec:
      containers:
      - name: control-center
        image: confluentinc/cp-enterprise-control-center:7.7.1
        ports:
        - containerPort: 9021   # ‚Üê you can change to 9020
        env:
        - name: CONTROL_CENTER_BOOTSTRAP_SERVERS
          value: "kafka"
        - name: CONTROL_CENTER_SCHEMA_REGISTRY_URL
          value: "http"
        - name: CONTROL_CENTER_CONNECT_CONNECT-DEFAULT_CLUSTER
          value: "connect"
        - name: CONTROL_CENTER_REPLICATION_FACTOR
          value: "1"
        - name: CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS
          value: "1"
        - name: CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS
          value: "1"
        - name: CONFLUENT_METRICS_TOPIC_REPLICATION
          value: "1"
        - name: CONTROL_CENTER_KAFKA_CLUSTER_ID
          value: "MkU3OEVBNTcwNTJENDM2Qk"