
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafbat-ui
  labels:
    app: kafbat-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafbat-ui
  template:
    metadata:
      labels:
        app: kafbat-ui
    spec:
      containers:
      - name: kafbat-ui
        image: ghcr.io/kafbat/kafka-ui:latest
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_CLUSTER_0_NAME
          value: "local"
        - name: KAFKA_CLUSTER_0_BOOTSTRAPSERVERS
          value: "kafka"
        - name: KAFKA_CLUSTER_0_SCHEMAREGISTRY
          value: "http"