
apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-service
  labels:
    app: posts-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts-service
  template:
    metadata:
      labels:
        app: posts-service
    spec:
      containers:
      - name: posts-service
        image: manishrnl/linked-in-app-post-service:latest
        ports:
        # No ports specified
        env:
        - name: KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL
          value: "http"
        - name: JAVA_OPTS
          value: "-Xmx256m"
        - name: EUREKA_SERVER_ADDRESS
          value: "http"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc"
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"
        - name: EUREKA_INSTANCE_NON_SECURE_PORT
          value: "8002"
        - name: SERVER_PORT
          value: "8002"
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "create-drop"
        - name: SPRING_JPA_SHOW_SQL
          value: "true"
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
          value: "true"
        - name: SPRING_JPA_DATABASE_PLATFORM
          value: "org.hibernate.dialect.PostgreSQLDialect"
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
          value: "org.hibernate.dialect.PostgreSQLDialect"