
apiVersion: v1
kind: Service
metadata:
  name: connect
  labels:
    app: connect
spec:
  type: LoadBalancer
  selector:
    app: connect
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP