
apiVersion: v1
kind: Service
metadata:
  name: connections-db
  labels:
    app: connections-db
spec:
  type: LoadBalancer
  selector:
    app: connections-db
  ports:
  - port: 7474
    targetPort: 7474
    protocol: TCP
  - port: 7687
    targetPort: 7687
    protocol: TCP