
apiVersion: v1
kind: Service
metadata:
  name: control-center
  labels:
    app: control-center
spec:
  type: LoadBalancer
  selector:
    app: control-center
  ports:
  - port: 9021
    targetPort: 9021   # ‚Üê you can change to 9020
    protocol: TCP