
apiVersion: v1
kind: Service
metadata:
  name: kafbat-ui
  labels:
    app: kafbat-ui
spec:
  type: LoadBalancer
  selector:
    app: kafbat-ui
  ports:
  - port: 8090
    targetPort: 8080
    protocol: TCP